export const stringJson = `{
  "label":"",
  "routePath":"",
  "mdPath":"",
  "keyWords":[
      {
          "label":"react",
          "routePath":"/react",
          "mdPath":"/reactindex.md",
          "keyWords":[
              {
                  "label":"diff",
                  "routePath":"/react/diff",
                  "mdPath":"./pages/markdown/react/diff.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"fiber",
                  "routePath":"/react/fiber",
                  "mdPath":"./pages/markdown/react/fiber.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"hooks",
                  "routePath":"/react/hooks",
                  "mdPath":"./pages/markdown/react/hooks.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"key",
                  "routePath":"/react/key",
                  "mdPath":"./pages/markdown/react/key.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"redux",
                  "routePath":"/react/redux",
                  "mdPath":"./pages/markdown/react/redux.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"update",
                  "routePath":"/react/update",
                  "mdPath":"./pages/markdown/react/update.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              }
          ]
      },
      {
          "label":"vue",
          "routePath":"/vue",
          "mdPath":"/vueindex.md",
          "keyWords":[
              {
                  "label":"diff",
                  "routePath":"/vue/diff",
                  "mdPath":"./pages/markdown/vue/diff.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"key",
                  "routePath":"/vue/key",
                  "mdPath":"./pages/markdown/vue/key.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"vuex",
                  "routePath":"/vue/vuex",
                  "mdPath":"./pages/markdown/vue/vuex.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"watch",
                  "routePath":"/vue/watch",
                  "mdPath":"./pages/markdown/vue/watch.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              }
          ]
      },
      {
          "label":"webBrowser",
          "routePath":"/webBrowser",
          "mdPath":"/webBrowserindex.md",
          "keyWords":[
              {
                  "label":"cookie",
                  "routePath":"/webBrowser/cookie",
                  "mdPath":"./pages/markdown/webBrowser/cookie.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"crossPage",
                  "routePath":"/webBrowser/crossPage",
                  "mdPath":"./pages/markdown/webBrowser/crossPage.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"memory",
                  "routePath":"/webBrowser/memory",
                  "mdPath":"./pages/markdown/webBrowser/memory.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"performance",
                  "routePath":"/webBrowser/performance",
                  "mdPath":"./pages/markdown/webBrowser/performance.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"pwa",
                  "routePath":"/webBrowser/pwa",
                  "mdPath":"./pages/markdown/webBrowser/pwa.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"safety",
                  "routePath":"/webBrowser/safety",
                  "mdPath":"./pages/markdown/webBrowser/safety.md",
                  "keyWords":[
                    "错误收集","错误上报","promise/vue/react错误"
                  ]
              },
              {
                  "label":"webTest",
                  "routePath":"/webBrowser/webTest",
                  "mdPath":"/webBrowser/webTestindex.md",
                  "keyWords":[
                      {
                          "label":"webTestKey",
                          "routePath":"/webBrowser/webTest/webTestKey",
                          "mdPath":"./pages/markdown/webBrowser/webTest/webTestKey.md",
                          "keyWords":[
                            "错误收集","错误上报","promise/vue/react错误"
                          ]
                      }
                  ]
              }
          ]
      }
  ]
}`