const routes = [{
  label:'react',
  mdPath:"./pages/react/index.md",
  routePath:'/react',
  keyWords:[{
    keyWords:[],
    mdPath:"./pages/react/key.md",
    routePath:'/react/key',
    label:'key'
  },{
    keyWords:[],
    mdPath:"./pages/react/hooks.md",
    routePath:'/react/hooks',
    label:'hooks'
  },{
    keyWords:[],
    mdPath:"./pages/react/fiber.md",
    routePath:'/react/fiber',
    label:'fiber'
  },{
    keyWords:[],
    mdPath:"./pages/react/diff.md",
    routePath:'/react/diff',
    label:'diff'
  },{
    keyWords:[],
    mdPath:"./pages/react/update.md",
    routePath:'/react/update',
    label:'update'
  },{
    keyWords:[],
    mdPath:"./pages/react/redux.md",
    routePath:'/react/redux',
    label:'redux'
  }],
},{
  label:'vue',
  mdPath:"./pages/vue/index.md",
  routePath:'/vue',
  keyWords:[{
    keyWords:[],
    mdPath:"./pages/vue/key.md",
    routePath:'/vue/key',
    label:'key'
  },{
    keyWords:[],
    mdPath:"./pages/vue/diff.md",
    routePath:'/vue/diff',
    label:'diff'
  },{
    keyWords:[],
    mdPath:"./pages/vue/watch.md",
    routePath:'/vue/watch',
    label:'watch'
  },{
    keyWords:[],
    mdPath:"./pages/vue/vuex.md",
    routePath:'/vue/vuex',
    label:'vuex'
  }],
},{
  label:'浏览器相关',
  mdPath:"./pages/webBrowser/index.md",
  routePath:'/webBrowser',
  keyWords:[{
    keyWords:[],
    mdPath:"./pages/webBrowser/cookie.md",
    routePath:'/webBrowser/cookie',
    label:'cookie'
  },{
    keyWords:[],
    mdPath:"./pages/webBrowser/crossPage.md",
    routePath:'/webBrowser/crossPage',
    label:'crossPage'
  },{
    keyWords:[],
    mdPath:"./pages/webBrowser/memory.md",
    routePath:'/webBrowser/memory',
    label:'memory'
  },{
    keyWords:[],
    mdPath:"./pages/webBrowser/performance.md",
    routePath:'/webBrowser/performance',
    label:'performance'
  },{
    keyWords:[],
    mdPath:"./pages/webBrowser/pwa.md",
    routePath:'/webBrowser/pwa',
    label:'pwa'
  },{
    keyWords:[],
    mdPath:"./pages/webBrowser/safety.md",
    routePath:'/webBrowser/safety',
    label:'safety'
  }],
}]
  let asdfasf = []
  const rec = (storeArr,routesArr)=>{
    if(storeArr.length > 0){
      storeArr.forEach(key=>{
        routesArr.push(`<Route path="${key.routePath}" key="${key.routePath}" exact>{AsyncCompoennt(import("${key.mdPath}"))}</Route>`)
        rec(key.keyWords,routesArr)
      })
    }
  }
  rec(routes,asdfasf)
  console.log(asdfasf.join('\n'))